
# Setup
title:               Import numpy as np
tagline:             'notetaking as a machine learning engineer'
description:         "Kertansul's Blog"
urt:                 http://kertansul.github.io
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Shawn Chen
  url:               https://github.com/kertansul
  email:             kertansul@gmail.com

# Custom vars
version:             0.3.2
