
# Setup
title:               import numpy as my
tagline:             'notetaking as a machine learning engineer'
description:         "Kertansul's Blog"
urt:                 http://kertansul.github.io
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Shawn Chen
  url:               https://github.com/kertansul
  email:             kertansul@gmail.com

# Custom vars
version:             1.2.0

# Build settings
kramdown:
  parse_block_html:  true
plugins:
  - jekyll-seo-tag
