
# Setup
title:               Hello World
tagline:             'notetaking as a software engineer'
description:         ''
url:                 http://kertansul.github.io
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Shawn Chen
  url:               https://github.com/kertansul
  email:             kertansul@gmail.com

# Custom vars
version:             0.3.1
